# alphabetical order
1password, state=present, env=company
1password-cli, state=present, env=company
adoptopenjdk11, state=absent
android-studio
android-file-transfer, state=absent
atom, state=absent
bartender, state=present, env=company
daisydisk
discord, state=present, env=personal
discord, state=absent, env=company
docker-desktop, state=present, env=personal
docker-desktop, state=present, env=company
charles
claude-code, state=present, env=company
corretto@21
coteditor
dropbox, state=absent
elmedia-player, state=absent
firefox
google-chrome, state=absent, env=company
google-chrome, state=present, env=personal
google-cloud-sdk
google-japanese-ime
intellij-idea
iterm2
java8, state=absent
jad, state=absent
jd-gui, state=absent
jetbrains-toolbox, state=absent
karabiner-elements
realm-browser, state=absent
meetingbar, state=present, env=company
megasync, state=absent
nightingale, state=absent
onedrive, state=absent
paintbrush
pycharm, state=present, env=personal
pycharm, state=present, env=company
qbittorrent, state=present, env=personal
qbittorrent, state=absent, env=company
rancher, state=absent, env=personal
rancher, state=absent, env=company
rar
scroll-reverser, state=absent
skype, state=absent
slack, state=present, env=personal
slack, state=absent, env=company
slack-beta, state=absent
temurin@8
temurin@11
temurin@17
temurin@21, state=absent, env=personal
temurin@21, state=absent, env=company
visual-studio-code
visualvm
vlc, state=present, env=personal
zappy
zoom, state=present, env=personal
zoom, state=present, env=company
