# alphabetical order
apache-geode, state=absent
apktool
aria2
automake
autoconf
bat
bfg
binutils
carthage, state=absent
cf-cli
clang-format
cmake
composer
coreutils
curl
dart-sdk, state=absent
detect-secrets
dex2jar
dos2unix
# digdag
# elasticsearch
findutils
fish
flyctl
fontforge
fzf
ghkw
gh
git
git-lfs
gnupg
gnu-sed
go
golang-migrate
hashicorp/tap/terraform, state=absent
heroku
httpd
httpie, state=absent
hub
hugo, state=absent
imagemagick
instantclient-basic
instantclient-sqlplus
jpegoptim
jq
jwt-cli
kafka, state=absent
kubectl
kustomize
lame
lha, state=absent
libmemcached
libxml2 # for PHP
libxslt # for Python's lxml
lua
lynx
mas
# mcrypt  # for PHP
memcached
# mongodb
mplayer
mysql, state=absent
mysql@5.7, state=absent
mysql@8.0, state=absent
neovim
openssl@3
optipng
pidcat
pinentry-mac
pkg-config
plantuml
postgresql
protobuf
pwgen
reattach-to-user-namespace
readline
redis
rename
# sbt
sevenzip
sl
sqlite
tfenv
the_silver_searcher
thefuck, state=absent
tmux
tomcat
unar
uv
watch
webp
wget
xz
yq
zlib
