packages:
  - automake
  - autoconf
  - cmake
  - exuberant-ctags
  - gcc
  - g++
  - git
  - curl
  - libbz2-dev      # for Python
  - libexpat1-dev   # for Perl (XML::Parser)
  - libgmp3-dev     # for Perl
  - libreadline-dev # for Ruby
  - libssl-dev      # for Python
  - make
  - memcached
  - neovim
  - pkg-config
  - python-software-properties # for `add-repository` cmd
  - screen
  - silversearcher-ag
  - sl
  - unrar
  - vim-gnome
  - wget
  - zsh
