packages:
  - automake
  - autoconf
  - binutils
  - cmake
  - curl
  - jad
  - mplayer
  - neovim
  - openssl
  - pkg-config
  - readline
  - the_silver_searcher
  - unrar
  - wget

caskPackages:
  - bartender
  - dropbox
  - firefox
  - google-chrome
  - google-chrome-canary
  - intellij-idea
  - iterm2
  - megasync
  - nightingale
  - scroll-reverser
  - skype
