# alphabetical order
packages:
  - apktool
  - automake
  - autoconf
  - binutils
  - carthage
  - cf-cli
  - cmake
  - composer
  - coreutils
  - curl
  - dart
  - findutils
  - fontforge
  - gnupg
  - imagemagick
  - lame
  - lha
  - libmemcached
  - libxml2 # for PHP
  - mcrypt  # for PHP
  - memcached
  - mongodb
  - mplayer
  - mysql
  - neovim
  - openssl
  - pidcat
  - pkg-config
  - pwgen
  - readline
  - redis
  - rename
  - sbt
  - sl
  - the_silver_searcher
  - typesafe-activator
  - unar
  - unrar
  - wget

caskPackages:
  - android-studio
  - atom
  - bartender
  - docker
  - charles
  - dropbox
  - firefox
  - google-chrome
  - google-chrome-canary
  - google-japanese-ime
  - iterm2
  - java
  - jad
  - karabiner
  - megasync
  - nightingale
  - paintbrush
  - reflector
  - scroll-reverser
  - skype
