# alphabetical order
packages:
  - apktool
  - automake
  - autoconf
  - binutils
  - cmake
  - coreutils
  - curl
  - dart
  - gnupg2
  - lha
  - libmemcached
  - libxml2 # for PHP
  - mcrypt  # for PHP
  - memcached
  - mplayer
  - mysql@5.6
  - neovim
  - openssl
  - pidcat
  - pkg-config
  - readline
  - redis
  - the_silver_searcher
  - unrar
  - wget

caskPackages:
  - android-studio
  - atom
  - bartender
  - dropbox
  - firefox
  - google-chrome
  - google-chrome-canary
  - intellij-idea
  - iterm2
  - java
  - jad
  - karabiner
  - megasync
  - nightingale
  - paintbrush
  - scroll-reverser
  - skype
