# alphabetical order
packages:
  - apktool
  - automake
  - autoconf
  - binutils
  - carthage
  - cf-cli
  - clang-format
  - cmake
  - composer
  - coreutils
  - curl
  - dart
  - digdag
  - findutils
  - fish
  - fontforge
  - ghkw
  - git-lfs
  - gnupg
  - heroku
  - imagemagick
  - jpegoptim
  - lame
  - lha
  - libmemcached
  - libxml2 # for PHP
  - mcrypt  # for PHP
  - libxslt # for Python's lxml
  - memcached
  - mongodb
  - mplayer
  - mysql
  - neovim
  - openssl
  - optipng
  - pidcat
  - pkg-config
  - pwgen
  - reattach-to-user-namespace
  - readline
  - redis
  - rename
  - sbt
  - sl
  - the_silver_searcher
  - thefuck
  - tmux
  - typesafe-activator
  - unar
  - unrar
  - wget

caskPackages:
  - android-studio
  - android-file-transfer
  - atom
  - bartender
  - docker
  - charles
  - dropbox
  - firefox
  - google-chrome
  - google-chrome-canary
  - google-japanese-ime
  - iterm2
  - java
  - jad
  - karabiner
  - realm-browser
  - megasync
  - nightingale
  - paintbrush
  - reflector
  - scroll-reverser
  - skype
  - skitch
  - visual-studio-code
