files:
  - file: { path: .config/fish/config.fish }
  - file: { path: .config/fish/fish_plugins }
  - file: { path: .config/fish/conf.d/google-cloud-sdk.fish }
  - file: { path: .config/nvim/init.lua }
  - file: { path: .config/mise/conf.d/settings.toml }
  - file: { path: .editorconfig }
  - file: { path: .gemrc }
  - file: { path: .gitconfig }
  - file: { path: .gitconfig-personal }
  - file: { path: .gitignore }
  - file: { path: .gnupg/gpg-agent.conf }
  - file: { path: .screenrc }
  - file: { path: .tmux.conf }

directories:
  - path: .go
  - path: bin
  - path: opt
  - path: project
  - path: tmp
  - path: var
