update: true
upgrade: true

taps:
  - caskroom/cask
  - caskroom/versions
  - dart-lang/dart
  - cloudfoundry/tap
  - heroku/brew
  - homebrew/binary
  - homebrew/core
  - homebrew/php
  - homebrew/versions
  - neovim/neovim
